import { IPlayer, VOCATION } from '../playerModel'

const recordPlayersByVocation: Record<VOCATION, IPlayer> = {
  [VOCATION.NARUTO]: {
    id: 1,
    name: 'Naruto',
    group_id: 1,
    account_id: 1,
    level: 100,
    vocation: VOCATION.NARUTO,
    healthmax: 1000,
    experience: 100000,
    looktype: 1,
    maglevel: 50,
    manamax: 500,
    soul: 100,
    cap: 100,
    lastlogin: Date.now(),
    lastlogout: Date.now(),
    onlinetime: 3600, // 1 hour
    stamina: 100,
    skill_fist: 80,
    skill_club: 70,
    skill_sword: 90,
    skill_axe: 85,
    skill_dist: 95,
    skill_shielding: 75,
    skill_fishing: 60
  },
  [VOCATION.SAKURA]: {
    id: 2,
    name: 'Sakura',
    group_id: 1,
    account_id: 1,
    level: 90,
    vocation: VOCATION.SAKURA,
    healthmax: 900,
    experience: 90000,
    looktype: 2,
    maglevel: 40,
    manamax: 400,
    soul: 90,
    cap: 90,
    lastlogin: Date.now(),
    lastlogout: Date.now(),
    onlinetime: 7200, // 2 hours
    stamina: 95,
    skill_fist: 75,
    skill_club: 65,
    skill_sword: 85,
    skill_axe: 80,
    skill_dist: 90,
    skill_shielding: 70,
    skill_fishing: 55
  },
  [VOCATION.SASUKE]: {
    id: 3,
    name: 'Sasuke',
    group_id: 1,
    account_id: 1,
    level: 95,
    vocation: VOCATION.SASUKE,
    healthmax: 950,
    experience: 95000,
    looktype: 3,
    maglevel: 45,
    manamax: 450,
    soul: 95,
    cap: 95,
    lastlogin: Date.now(),
    lastlogout: Date.now(),
    onlinetime: 5400, // 1.5 hours
    stamina: 98,
    skill_fist: 78,
    skill_club: 68,
    skill_sword: 88,
    skill_axe: 83,
    skill_dist: 93,
    skill_shielding: 73,
    skill_fishing: 58
  },
  [VOCATION.NEJI]: {
    id: 4,
    name: 'Neji',
    group_id: 1,
    account_id: 1,
    level: 85,
    vocation: VOCATION.NEJI,
    healthmax: 850,
    experience: 85000,
    looktype: 4,
    maglevel: 35,
    manamax: 350,
    soul: 85,
    cap: 85,
    lastlogin: Date.now(),
    lastlogout: Date.now(),
    onlinetime: 1800, // 30 minutes
    stamina: 90,
    skill_fist: 70,
    skill_club: 60,
    skill_sword: 80,
    skill_axe: 75,
    skill_dist: 85,
    skill_shielding: 65,
    skill_fishing: 50
  },
  [VOCATION.LEE]: {
    id: 5,
    name: 'Lee',
    group_id: 1,
    account_id: 1,
    level: 80,
    vocation: VOCATION.LEE,
    healthmax: 800,
    experience: 80000,
    looktype: 5,
    maglevel: 30,
    manamax: 300,
    soul: 80,
    cap: 80,
    lastlogin: Date.now(),
    lastlogout: Date.now(),
    onlinetime: 2700, // 45 minutes
    stamina: 85,
    skill_fist: 65,
    skill_club: 55,
    skill_sword: 75,
    skill_axe: 70,
    skill_dist: 80,
    skill_shielding: 60,
    skill_fishing: 45
  },
  [VOCATION.TENTEN]: {
    id: 6,
    name: 'Tenten',
    group_id: 1,
    account_id: 1,
    level: 75,
    vocation: VOCATION.TENTEN,
    healthmax: 750,
    experience: 75000,
    looktype: 6,
    maglevel: 25,
    manamax: 250,
    soul: 75,
    cap: 75,
    lastlogin: Date.now(),
    lastlogout: Date.now(),
    onlinetime: 900, // 15 minutes
    stamina: 80,
    skill_fist: 60,
    skill_club: 50,
    skill_sword: 70,
    skill_axe: 65,
    skill_dist: 75,
    skill_shielding: 55,
    skill_fishing: 40
  },
  [VOCATION.CHOUJI]: {
    id: 7,
    name: 'Chouji',
    group_id: 1,
    account_id: 1,
    level: 70,
    vocation: VOCATION.CHOUJI,
    healthmax: 700,
    experience: 70000,
    looktype: 7,
    maglevel: 20,
    manamax: 200,
    soul: 70,
    cap: 70,
    lastlogin: Date.now(),
    lastlogout: Date.now(),
    onlinetime: 7200, // 2 hours
    stamina: 75,
    skill_fist: 55,
    skill_club: 45,
    skill_sword: 65,
    skill_axe: 60,
    skill_dist: 70,
    skill_shielding: 50,
    skill_fishing: 35
  },
  [VOCATION.INO]: {
    id: 8,
    name: 'Ino',
    group_id: 1,
    account_id: 1,
    level: 65,
    vocation: VOCATION.INO,
    healthmax: 650,
    experience: 65000,
    looktype: 8,
    maglevel: 15,
    manamax: 150,
    soul: 65,
    cap: 65,
    lastlogin: Date.now(),
    lastlogout: Date.now(),
    onlinetime: 5400, // 1.5 hours
    stamina: 70,
    skill_fist: 50,
    skill_club: 40,
    skill_sword: 60,
    skill_axe: 55,
    skill_dist: 65,
    skill_shielding: 45,
    skill_fishing: 30
  },
  [VOCATION.SHIKAMARU]: {
    id: 9,
    name: 'Shikamaru',
    group_id: 1,
    account_id: 1,
    level: 60,
    vocation: VOCATION.SHIKAMARU,
    healthmax: 600,
    experience: 60000,
    looktype: 9,
    maglevel: 10,
    manamax: 100,
    soul: 60,
    cap: 60,
    lastlogin: Date.now(),
    lastlogout: Date.now(),
    onlinetime: 1800, // 30 minutes
    stamina: 65,
    skill_fist: 45,
    skill_club: 35,
    skill_sword: 55,
    skill_axe: 50,
    skill_dist: 60,
    skill_shielding: 40,
    skill_fishing: 25
  }
}

const mockPlayers: IPlayer[] = Object.values(recordPlayersByVocation)

export { mockPlayers }
