name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout files repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}

      - name: Update files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          source: ./
          target: /home/nto-global-repo/nto-web-spa/

      - name: Check if Docker is installed
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          script: |
            if ! command -v docker &> /dev/null; then
              echo "Docker is not installed"
              INSTALL_DOCKER=true
            else
              echo "Docker is already installed"
              INSTALL_DOCKER=false
            fi

      - name: Install Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          if: ${{ steps.check-docker.outputs.INSTALL_DOCKER == 'true' }}
          script: |
            sudo apt-get update
            sudo apt-get install -y docker.io

      - name: Build and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          script: |
            DEPLOY_PATH=$(find /home/nto-global-repo/nto-web-spa -name "deploy.sh" -type f)
            sh "$DEPLOY_PATH"
